export type BlogPost = {
  slug: string;
  title: string;
  excerpt: string;
  cover: string;
  content: string;
  date: string;
};

export const blogPosts: BlogPost[] = [
  {
    slug: "What-programming-looks-like-in-the-future",
    title: "The Future of Programming: Will Developers Still Code in 10 Years?",
    excerpt:
      "A discussion on whether developers will still be coding in the next decade as AI continues to evolve.",
    cover: "/blog/blog1img1.png",
    date: "2026-03-03",
    content: `
### The Future of Programming: Will Developers Still Code in 10 Years?  
-Aneshya Das


Everyone has seen the panic on their feeds by now. "An AI just built a functional website in 10 seconds. Software engineering is dead." It is the tech world's new favorite doomsday prophecy.

If you just look at the surface, it’s easy to believe. You ask a chatbot for a standard React component or a basic data fetching function, and it spits it out flawlessly before you’ve even taken a sip of your coffee. If that is what you think "coding" is, then yes, the future looks pretty bleak for human developers.


But let’s take a collective breath and look at what is actually happening. We aren't witnessing the death of programming; we are watching the death of the "syntax typist."

Let me break down why the developer of 2036 will still be very much employed, just doing a completely different job.


Layer 1: The New Compiler Think about the history of computer science. Decades ago, developers wrote in Assembly language—literally moving bits around in memory. Then came C, then Python, then high-level frameworks. Every time we added an abstraction layer, people panicked that "real coding" was dying.

AI is just the newest abstraction layer. It is the new compiler. We are moving away from writing boilerplate code and moving towards "orchestration." Instead of spending an hour setting up standard routing, we will delegate that to an AI agent. But the fundamental logic? That is still on us.


Layer 2: System Design Over Syntax This is where the reality check hits the AI hype. An AI is fantastic at writing isolated, single-file functions. But software is rarely an isolated function.

Ask an AI to generate a login form, and it wins. But ask an AI to securely connect a React frontend to an Express.js backend, route it through a MongoDB database, handle authentication tokens securely, and manage complex state across a massive user base without crashing? Suddenly, your "AI developer" gets confused, hallucinates, and breaks the build.

The same applies to machine learning. An AI can spit out the boilerplate Python script to build a neural network. But when your Convolutional Neural Network (CNN) starts wildly misclassifying data, or your NLP model struggles with complex, code-mixed data like Hinglish because of weird tokenization issues, AI cannot intuitively troubleshoot the data constraints.

Putting the puzzle pieces together, understanding edge cases, and ensuring security requires an overarching architectural vision. AI is the bricklayer; the developer is the architect.


Layer 3: The Debugging Nightmare If you think debugging your own code is painful, wait until you have to debug millions of lines of code generated by a black-box AI model that hallucinates 5% of the time.


![Debugging AI generated code](/blog/blog1img2.png)  
Image Source: gemini.google.com


As AI generates more code, the value of a developer who can actually read, trace, and fix complex system architectures will skyrocket. The future belongs to problem solvers, not code monkeys.


The Verdict Will we still "code" in 10 years? If by coding, you mean manually typing out every single bracket and semicolon, then probably not.

But if you mean breaking down complex human problems into logical, scalable, and secure technical systems? Absolutely. In fact, it's going to be more important than ever.

In the end, AI won't replace developers. But a developer who knows how to orchestrate AI will absolutely replace a developer who doesn't. So, keep building, keep debugging, and maybe just let the AI write your CSS.
`,
  },

  {
    slug: "digital-divide-2-ai-access",
    title: "Digital Divide 2.0: Who Gets Access to AI; and Who Doesn’t?",
    excerpt:
      "Digital Divide 2.0 explores how access to AI is no longer just about internet, but about capability, cost, and control.",
    cover: "/blog/blog2img1.png",
    date: "2026-02-28",
    content: `
### Digital Divide 2.0: Who Gets Access to AI; and Who Doesn’t?  
-Arni Goyal


“Do you have access to AI?”, they ask. And I am like, “Sorry, what? Do you mean to ask whether I have an internet connection?”


Yes, that question simply means what I clarified. And yes, the topic itself says it wrong. That’s the reason this topic was chosen. Because there will be two of many types of people, one would be those who know the actual fact and are here to criticise the blog in the comments, that the topic is all wrong, and others would be the not-so-aware ones (just like I was before reading about this), who are here to actually know the Digital Divide 2.0 and are not aware as of now.


So, coming to the point. Let’s clarify all the confusion that happened above. One of the major differences between Digital Divide 1.0 and Digital Divide 2.0 is that the former one was about whether you have an internet connection, and the latter one is about whether you have the capability. Giving everyone a violin doesn’t make everyone a musician. The world was given AI, but the music sheet wasn’t distributed. And thus in DD 2.0, we are not talking about having access, but we are talking about having the right skills to utilise that technology. 


But yes, talking globally, the topic after all isn’t that wrong as well. There is a divide. While the DD 1.0 was binary (online/offline), the DD 2.0 is tiered. Let me break it down into 3 different layers. 


Starting off with the first, we have the hardware gap. Let’s be real, AI isn’t some magic, it runs on physical hardware and electricity. The big servers are present in the global north (USA and China) and thus nearly 86-90% (source: https://epoch.ai/data-insights/ai-supercomputers-performance-share-by-country) compute capacity is controlled by them. And just like business works, developing countries have to pay rent for using the intelligence because they can’t build it. This has caused the birth of a movement called “Sovereign AI”. Countries like India, UAE, and France are trying to build their own data centers so that they aren’t dependent on big tech giants.


![AI data centers infrastructure](/blog/blog2img2.png)  
Image Source: gemini.google.com 


The next layer that comes into play is the algorithmic bias or the “Language Tax”. This is somewhat related to the technical part. Basically, behind the scenes the AI model processes words in the form of tokens. In English, this method is highly optimizied as 1 word is nearly equal to 1 token, but in languages like Hindi, Burmese etc., 1 word nearly equals 3-4 tokens, just because the model isn’t optimized for those languages. This hidden tax increases the cost of using AI in languages other than English. 


The third layer which enters is the “Privacy Premium”. In today’s world privacy has become a luxury item. The large and wealthy firms can easily pay for the “private instances” where their data is not used for training, but normal users and small firms pay with their data. Every prompt, every detail they enter is used for training the chatbot. In short, the rich own their IP and the poor feed the machine. 


![Data privacy concept](/blog/blog2img3.png)  
Image Source: gemini.google.com 


From these 3 layers it is clearly evident that the divide is not who can access AI and who cannot, but in how they can access. One thing I found nostalgic was the colonialism. Just like in the past, colonial powers purchased raw materials like cotton, indigo and sold back finished products, similarly now big giants are extracting data from the open web and selling back processed intelligence. Capitalism really looked at the 1700s and said, “Let’s do that again, but make it a $20 monthly subscription”.


To wrap this up, I would say that yes all those having internet have access to AI but how much and at what cost is where the division lies. You have money, then feed it to the machine and voila! you can do everything without being worried about which language to use and the safety of your data. But if you don’t, then it depends on many factors including your location, your mother tongue etc. All in all I would say that Digital Divide 2.0 is basically a Dementor's Kiss, but instead of sucking out your soul, they suck out your entire chat history and sell it back to you as a ‘copilot’.


`,
  },

  {
    slug: "is-cloud-really-cheaper",
    title: "Is the Cloud Really Cheaper? A Data-Driven Cost Comparison",
    excerpt:
      "A clear, data-driven comparison of cloud vs on-prem infrastructure costs and when each makes financial sense.",
    cover: "/blog/blog3img1.png",
    date: "2026-02-25",
    content: `
### Is the Cloud Really Cheaper? A Data-Driven Cost Comparison


“Cloud is cheaper.”


It’s one of the most repeated statements in modern tech.


But is it actually true?


The honest answer: it depends on what you’re running, how you’re running it, and how long you plan to run it.


Let’s break it down with logic, numbers, and real-world context.


### Step 1: What Are We Comparing?


There are two fundamentally different cost models.


🏢 On-Premises Infrastructure


You buy and manage:
Physical servers
Storage systems
Networking equipment
Power and cooling
IT staff


You own the hardware.
You handle failures.
You replace equipment every few years.


☁️ Cloud Infrastructure


You rent computing resources from providers like:


Amazon Web Services
Microsoft Azure
Google Cloud Platform


No physical hardware.
No large upfront investment.
You pay monthly, based on usage.


Different ownership. Different financial behavior.



### Step 2: The Cost Breakdown (With Numbers)


Let’s take a realistic example.


Scenario:


A growing web application needs:
3 application servers
1 database server
2 TB storage
Moderate traffic


Option A: On-Prem Costs (3-Year Estimate)


Upfront costs:


Servers: ~$40,000
Networking & setup: ~$15,000
Backup & redundancy: ~$10,000
Installation & configuration: ~$10,000


Initial total: ~$75,000


Operational costs (3 years)
Power & cooling: ~$12,000
Maintenance contracts: ~$18,000


Total over 3 years:
👉 ~$100,000+


And that’s before scaling.


Option B: Cloud Costs (3-Year Estimate)


Estimated monthly usage:
Compute: ~$500
Storage: ~$60
Data transfer: ~$100


Monthly total: ~$660


3-year total:
👉 ~$23,760


Even if we double that for growth and overhead:
👉 ~$45,000


In this case, cloud is significantly cheaper.
But that doesn’t mean it always is.



### When the Cloud Is Clearly Cheaper


1️⃣ Startups & Early-Stage Companies


Startups usually don’t have $100K to invest in infrastructure.


Cloud allows them to:
Launch quickly
Start small
Scale gradually
Avoid upfront capital risk


Speed matters more than hardware ownership at this stage.


2️⃣ Unpredictable Traffic


If usage fluctuates:
Seasonal spikes
Marketing campaigns
Viral growth


Cloud automatically scales.


With on-prem, you either:
Overbuy hardware (wasted money), or
Underestimate and crash.


3️⃣ Experimentation & Innovation


Cloud lets you:
Spin up servers in minutes
Test new features
Shut things down instantly


That flexibility reduces risk and encourages innovation.
And innovation often drives revenue.


### When On-Prem Can Be Cheaper


1️⃣ Stable, High-Utilization Workloads


If your systems:
Run 24/7
Operate at 80–90% utilization
Remain predictable for years


Owning hardware may become cheaper long term.


This is why some large-scale companies rethink cloud-heavy strategies.


For example, Dropbox moved significant workloads to custom infrastructure once they reached massive scale to reduce long-term costs.


At that level, small efficiency improvements mean millions saved.


2️⃣ Heavy Data Transfer


Cloud providers often charge for outbound data.
If your business:
Streams video
Transfers large datasets
Serves global high-volume traffic


Data egress fees can quietly increase your bill.


3️⃣ Poor Cost Management


Cloud is easy to start.
It’s also easy to overspend.
Common issues: 
Idle instances
Oversized virtual machines
Forgotten storage
Lack of monitoring


Without discipline, monthly bills grow fast.



### The Financial Psychology: CapEx vs OpEx


On-prem requires CapEx (capital expenditure).
Big upfront payment. Asset ownership.


Cloud shifts to OpEx (operational expenditure).
Smaller recurring payments.


Cloud feels cheaper because:
You don’t pay everything at once.
Monthly bills seem manageable.


But over 5–7 years, subscription-style infrastructure can accumulate significantly.


Cloud doesn’t eliminate cost.
It changes the timing and structure of cost.


### So… Is the Cloud Really Cheaper?


✅ Yes, if:
You’re a startup or scaling company
Workloads are unpredictable
Speed and flexibility are priorities
You want low upfront risk


❌ Not always, if:
Workloads are stable and heavy
Utilization stays consistently high
You operate at massive scale


### The Modern Strategy: Hybrid Thinking


Today, many organizations don’t choose one extreme.


They combine:
Stable core systems on owned infrastructure.
Dynamic, scalable workloads in the cloud.


It’s not about trends.
It’s about financial alignment with business goals.
`,
  },

  {
    slug: "digital-burnout-students-productivity",
    title: "The Rise of Digital Burnout: Is Technology Making Students Less Productive?",
    excerpt:
      "An exploration of how constant digital engagement is affecting student focus, productivity, and mental energy.",
    cover: "/blog/blog4img1.png",
    date: "2026-02-28",
    content: `
### The Rise of Digital Burnout: Is Technology Making Students Less Productive?


Have you ever felt exhausted after a full day of being online even though you barely moved from your chair?


It is 11:47 PM. You sit in front of your screen with five tabs open, a lecture playing faintly in the background, your phone lighting up every few minutes. The deadline is tomorrow. Your eyes burn. Your mind is exhausted. Yet you keep scrolling, trapped between urgency and distraction.


This is not laziness. It is digital burnout.

Digital burnout does not arrive suddenly. It builds quietly, one notification at a time, one unfinished tab at a time, one late-night scroll at a time. Your brain is forced to constantly switch contexts: lecture to message, message to email, email to social media. Each shift feels harmless on its own, but together they fracture attention. Tasks stretch longer. Retention weakens. Even while studying, part of your mind remains elsewhere.


Technology was meant to make learning efficient, yet it often promotes surface-level engagement. Lectures are played at double speed. Notes are skimmed instead of processed. Assignments are completed while replying to texts. The work gets finished, but the depth is missing. Productivity becomes performance, about how busy you appear, rather than how well you understand.


The most dangerous part is how normal this feels. Sleeping after midnight becomes routine. Multitasking feels inevitable. Because everyone studies this way, no one questions it. Over time, divided attention erodes memory, dulls creativity, and increases anxiety, not because students lack discipline, but because their cognitive energy is constantly overstimulated.


Consider a typical classroom. A professor explains a complex concept while half the class checks notifications under their desks. A quick glance becomes minutes of distraction. Later, those same students spend hours relearning what they could have understood in real time. The time was invested. The focus was not.


Research consistently shows that interruptions reduce productivity and that the brain requires significant time to regain deep focus after switching tasks. Constant digital engagement creates cognitive overload, a state in which the brain absorbs more stimuli than it can meaningfully process. The result is mental fatigue disguised as accomplishment.


Technology itself is not the enemy. It has expanded access to knowledge and transformed education in powerful ways. The real problem is the erosion of boundaries. When students are always available, always responsive, and always connected, rest begins to feel irresponsible.


Over time, productivity shifts from deep concentration to visible busyness. Tabs remain open. Notifications are answered. Tasks are checked off. But genuine understanding requires uninterrupted thought, something increasingly rare in a world engineered to capture attention.


The solution is not to reject technology, but to reclaim authority over it. Turn off what does not matter. Protect what does. Create space where your attention is not constantly negotiated. Depth is not accidental. It is defended.


It is still 11:47 PM. The screen is still glowing.


Nothing dramatic will happen if you keep scrolling. Just another divided minute, then another. This is how focus disappears, not in crisis, but in quiet surrender.


Close the tabs.


Or allow them to quietly determine how deeply you think, how clearly you learn and how far you go.
`,
  },
];